sonar.projectKey=devsetgo_mrie
sonar.organization=devsetgo
sonar.projectName=mrie
sonar.language=python
sonar.python.version=3.14
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=**/tests/*.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/static/**,**/templates/**
sonar.sourceEncoding=UTF-8
