# -*- coding: utf-8 -*-
"""baseline: existing schema

Revision ID: aba742792ce0
Revises:
Create Date: 2026-09-13 21:04:03.518261

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "aba742792ce0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "about_page",
        sa.Column("content", sa.String(), nullable=False),
        sa.Column(
            "pkid",
            sa.String(length=36),
            nullable=False,
            comment="Unique identifier for each record, a string representation of a UUID",
        ),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=True,
            comment="Date and time when a row was inserted, defaults to current UTC time",
        ),
        sa.Column(
            "date_updated",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=True,
            comment="Date and time when a row was last updated, defaults to current UTC time on update",
        ),
        sa.PrimaryKeyConstraint("pkid"),
    )
    op.create_index(
        op.f("ix_about_page_date_created"), "about_page", ["date_created"], unique=False
    )
    op.create_index(
        op.f("ix_about_page_date_updated"), "about_page", ["date_updated"], unique=False
    )
    op.create_index(op.f("ix_about_page_pkid"), "about_page", ["pkid"], unique=False)
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("is_post", sa.Boolean(), nullable=True),
        sa.Column("is_weblink", sa.Boolean(), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=True),
        sa.Column(
            "pkid",
            sa.String(length=36),
            nullable=False,
            comment="Unique identifier for each record, a string representation of a UUID",
        ),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=True,
            comment="Date and time when a row was inserted, defaults to current UTC time",
        ),
        sa.Column(
            "date_updated",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=True,
            comment="Date and time when a row was last updated, defaults to current UTC time on update",
        ),
        sa.PrimaryKeyConstraint("pkid"),
    )
    op.create_index(
        op.f("ix_categories_date_created"), "categories", ["date_created"], unique=False
    )
    op.create_index(
        op.f("ix_categories_date_updated"), "categories", ["date_updated"], unique=False
    )
    op.create_index(
        op.f("ix_categories_description"), "categories", ["description"], unique=False
    )
    op.create_index(
        op.f("ix_categories_is_post"), "categories", ["is_post"], unique=False
    )
    op.create_index(
        op.f("ix_categories_is_system"), "categories", ["is_system"], unique=False
    )
    op.create_index(
        op.f("ix_categories_is_weblink"), "categories", ["is_weblink"], unique=False
    )
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=False)
    op.create_index(op.f("ix_categories_pkid"), "categories", ["pkid"], unique=False)
    op.create_table(
        "users",
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("user_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("provider", sa.String(), nullable=True),
        sa.Column("my_timezone", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("update_by", sa.String(), nullable=True),
        sa.Column("date_last_login", sa.DateTime(), nullable=True),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("roles", sa.JSON(), nullable=True),
        sa.Column("removal_flag", sa.DateTime(), nullable=True),
        sa.Column(
            "pkid",
            sa.String(length=36),
            nullable=False,
            comment="Unique identifier for each record, a string representation of a UUID",
        ),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=True,
            comment="Date and time when a row was inserted, defaults to current UTC time",
        ),
        sa.Column(
            "date_updated",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=True,
            comment="Date and time when a row was last updated, defaults to current UTC time on update",
        ),
        sa.PrimaryKeyConstraint("pkid"),
    )
    op.create_index(
        op.f("ix_users_date_created"), "users", ["date_created"], unique=False
    )
    op.create_index(
        op.f("ix_users_date_last_login"), "users", ["date_last_login"], unique=False
    )
    op.create_index(
        op.f("ix_users_date_updated"), "users", ["date_updated"], unique=False
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_first_name"), "users", ["first_name"], unique=False)
    op.create_index(op.f("ix_users_is_locked"), "users", ["is_locked"], unique=False)
    op.create_index(op.f("ix_users_last_name"), "users", ["last_name"], unique=False)
    op.create_index(
        op.f("ix_users_my_timezone"), "users", ["my_timezone"], unique=False
    )
    op.create_index(op.f("ix_users_pkid"), "users", ["pkid"], unique=False)
    op.create_index(
        op.f("ix_users_removal_flag"), "users", ["removal_flag"], unique=False
    )
    op.create_index(op.f("ix_users_update_by"), "users", ["update_by"], unique=False)
    op.create_index(op.f("ix_users_user_name"), "users", ["user_name"], unique=True)
    op.create_table(
        "note_metrics",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("character_count", sa.Integer(), nullable=True),
        sa.Column("note_count", sa.Integer(), nullable=True),
        sa.Column("mood_metric", sa.JSON(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("ai_fix_count", sa.Integer(), nullable=True),
        sa.Column("total_unique_tag_count", sa.Integer(), nullable=True),
        sa.Column(
            "pkid",
            sa.String(length=36),
            nullable=False,
            comment="Unique identifier for each record, a string representation of a UUID",
        ),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=True,
            comment="Date and time when a row was inserted, defaults to current UTC time",
        ),
        sa.Column(
            "date_updated",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=True,
            comment="Date and time when a row was last updated, defaults to current UTC time on update",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.pkid"],
        ),
        sa.PrimaryKeyConstraint("pkid"),
    )
    op.create_index(
        op.f("ix_note_metrics_date_created"),
        "note_metrics",
        ["date_created"],
        unique=False,
    )
    op.create_index(
        op.f("ix_note_metrics_date_updated"),
        "note_metrics",
        ["date_updated"],
        unique=False,
    )
    op.create_index(
        op.f("ix_note_metrics_pkid"), "note_metrics", ["pkid"], unique=False
    )
    op.create_index(
        op.f("ix_note_metrics_user_id"), "note_metrics", ["user_id"], unique=True
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.Column("note_id", sa.String(), nullable=True),
        sa.Column(
            "pkid",
            sa.String(length=36),
            nullable=False,
            comment="Unique identifier for each record, a string representation of a UUID",
        ),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=True,
            comment="Date and time when a row was inserted, defaults to current UTC time",
        ),
        sa.Column(
            "date_updated",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=True,
            comment="Date and time when a row was last updated, defaults to current UTC time on update",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.pkid"],
        ),
        sa.PrimaryKeyConstraint("pkid"),
    )
    op.create_index(
        op.f("ix_notifications_category"), "notifications", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_date_created"),
        "notifications",
        ["date_created"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_date_updated"),
        "notifications",
        ["date_updated"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_is_read"), "notifications", ["is_read"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_pkid"), "notifications", ["pkid"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False
    )
    op.create_table(
        "notes",
        sa.Column("mood", sa.String(length=500), nullable=True),
        sa.Column("mood_analysis", sa.String(length=500), nullable=True),
        sa.Column("_note", sa.LargeBinary(), nullable=False),
        sa.Column("_summary", sa.LargeBinary(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("character_count", sa.Integer(), nullable=True),
        sa.Column("ai_fix", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("demo_created", sa.Integer(), nullable=True),
        sa.Column(
            "pkid",
            sa.String(length=36),
            nullable=False,
            comment="Unique identifier for each record, a string representation of a UUID",
        ),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=True,
            comment="Date and time when a row was inserted, defaults to current UTC time",
        ),
        sa.Column(
            "date_updated",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=True,
            comment="Date and time when a row was last updated, defaults to current UTC time on update",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.pkid"],
        ),
        sa.PrimaryKeyConstraint("pkid"),
        schema="public",
    )
    op.create_index(
        "ix_notes__note_hash",
        "notes",
        [sa.literal_column("md5(_note)")],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_notes__summary"),
        "notes",
        ["_summary"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_notes_date_created"),
        "notes",
        ["date_created"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_notes_date_updated"),
        "notes",
        ["date_updated"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_notes_demo_created"),
        "notes",
        ["demo_created"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_notes_mood"), "notes", ["mood"], unique=False, schema="public"
    )
    op.create_index(
        op.f("ix_public_notes_mood_analysis"),
        "notes",
        ["mood_analysis"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_notes_pkid"), "notes", ["pkid"], unique=False, schema="public"
    )
    op.create_index(
        op.f("ix_public_notes_user_id"),
        "notes",
        ["user_id"],
        unique=False,
        schema="public",
    )
    op.create_table(
        "web_links",
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("public", sa.Boolean(), nullable=True),
        sa.Column(
            "image_preview_data",
            sa.LargeBinary(),
            nullable=True,
            comment="Binary data of the image preview of the webpage",
        ),
        sa.Column("ai_fix", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column(
            "pkid",
            sa.String(length=36),
            nullable=False,
            comment="Unique identifier for each record, a string representation of a UUID",
        ),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=True,
            comment="Date and time when a row was inserted, defaults to current UTC time",
        ),
        sa.Column(
            "date_updated",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=True,
            comment="Date and time when a row was last updated, defaults to current UTC time on update",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.pkid"],
        ),
        sa.PrimaryKeyConstraint("pkid"),
    )
    op.create_index(
        op.f("ix_web_links_category"), "web_links", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_web_links_comment"), "web_links", ["comment"], unique=False
    )
    op.create_index(
        op.f("ix_web_links_date_created"), "web_links", ["date_created"], unique=False
    )
    op.create_index(
        op.f("ix_web_links_date_updated"), "web_links", ["date_updated"], unique=False
    )
    op.create_index(op.f("ix_web_links_pkid"), "web_links", ["pkid"], unique=False)
    op.create_index(
        op.f("ix_web_links_summary"), "web_links", ["summary"], unique=False
    )
    op.create_index(op.f("ix_web_links_title"), "web_links", ["title"], unique=False)
    op.create_index(op.f("ix_web_links_url"), "web_links", ["url"], unique=False)
    op.create_table(
        "webauthn_credentials",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("credential_id", sa.String(), nullable=False),
        sa.Column("public_key", sa.LargeBinary(), nullable=False),
        sa.Column("sign_count", sa.Integer(), nullable=False),
        sa.Column("transports", sa.JSON(), nullable=True),
        sa.Column("device_name", sa.String(), nullable=True),
        sa.Column("date_last_used", sa.DateTime(), nullable=True),
        sa.Column(
            "pkid",
            sa.String(length=36),
            nullable=False,
            comment="Unique identifier for each record, a string representation of a UUID",
        ),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=True,
            comment="Date and time when a row was inserted, defaults to current UTC time",
        ),
        sa.Column(
            "date_updated",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=True,
            comment="Date and time when a row was last updated, defaults to current UTC time on update",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.pkid"],
        ),
        sa.PrimaryKeyConstraint("pkid"),
    )
    op.create_index(
        op.f("ix_webauthn_credentials_credential_id"),
        "webauthn_credentials",
        ["credential_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_webauthn_credentials_date_created"),
        "webauthn_credentials",
        ["date_created"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webauthn_credentials_date_updated"),
        "webauthn_credentials",
        ["date_updated"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webauthn_credentials_pkid"),
        "webauthn_credentials",
        ["pkid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webauthn_credentials_user_id"),
        "webauthn_credentials",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_webauthn_credentials_user_id"), table_name="webauthn_credentials"
    )
    op.drop_index(
        op.f("ix_webauthn_credentials_pkid"), table_name="webauthn_credentials"
    )
    op.drop_index(
        op.f("ix_webauthn_credentials_date_updated"), table_name="webauthn_credentials"
    )
    op.drop_index(
        op.f("ix_webauthn_credentials_date_created"), table_name="webauthn_credentials"
    )
    op.drop_index(
        op.f("ix_webauthn_credentials_credential_id"), table_name="webauthn_credentials"
    )
    op.drop_table("webauthn_credentials")
    op.drop_index(op.f("ix_web_links_url"), table_name="web_links")
    op.drop_index(op.f("ix_web_links_title"), table_name="web_links")
    op.drop_index(op.f("ix_web_links_summary"), table_name="web_links")
    op.drop_index(op.f("ix_web_links_pkid"), table_name="web_links")
    op.drop_index(op.f("ix_web_links_date_updated"), table_name="web_links")
    op.drop_index(op.f("ix_web_links_date_created"), table_name="web_links")
    op.drop_index(op.f("ix_web_links_comment"), table_name="web_links")
    op.drop_index(op.f("ix_web_links_category"), table_name="web_links")
    op.drop_table("web_links")
    op.drop_index(op.f("ix_public_notes_user_id"), table_name="notes", schema="public")
    op.drop_index(op.f("ix_public_notes_pkid"), table_name="notes", schema="public")
    op.drop_index(
        op.f("ix_public_notes_mood_analysis"), table_name="notes", schema="public"
    )
    op.drop_index(op.f("ix_public_notes_mood"), table_name="notes", schema="public")
    op.drop_index(
        op.f("ix_public_notes_demo_created"), table_name="notes", schema="public"
    )
    op.drop_index(
        op.f("ix_public_notes_date_updated"), table_name="notes", schema="public"
    )
    op.drop_index(
        op.f("ix_public_notes_date_created"), table_name="notes", schema="public"
    )
    op.drop_index(op.f("ix_public_notes__summary"), table_name="notes", schema="public")
    op.drop_index("ix_notes__note_hash", table_name="notes", schema="public")
    op.drop_table("notes", schema="public")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_pkid"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_is_read"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_date_updated"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_date_created"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_category"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_note_metrics_user_id"), table_name="note_metrics")
    op.drop_index(op.f("ix_note_metrics_pkid"), table_name="note_metrics")
    op.drop_index(op.f("ix_note_metrics_date_updated"), table_name="note_metrics")
    op.drop_index(op.f("ix_note_metrics_date_created"), table_name="note_metrics")
    op.drop_table("note_metrics")
    op.drop_index(op.f("ix_users_user_name"), table_name="users")
    op.drop_index(op.f("ix_users_update_by"), table_name="users")
    op.drop_index(op.f("ix_users_removal_flag"), table_name="users")
    op.drop_index(op.f("ix_users_pkid"), table_name="users")
    op.drop_index(op.f("ix_users_my_timezone"), table_name="users")
    op.drop_index(op.f("ix_users_last_name"), table_name="users")
    op.drop_index(op.f("ix_users_is_locked"), table_name="users")
    op.drop_index(op.f("ix_users_first_name"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_date_updated"), table_name="users")
    op.drop_index(op.f("ix_users_date_last_login"), table_name="users")
    op.drop_index(op.f("ix_users_date_created"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_categories_pkid"), table_name="categories")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_index(op.f("ix_categories_is_weblink"), table_name="categories")
    op.drop_index(op.f("ix_categories_is_system"), table_name="categories")
    op.drop_index(op.f("ix_categories_is_post"), table_name="categories")
    op.drop_index(op.f("ix_categories_description"), table_name="categories")
    op.drop_index(op.f("ix_categories_date_updated"), table_name="categories")
    op.drop_index(op.f("ix_categories_date_created"), table_name="categories")
    op.drop_table("categories")
    op.drop_index(op.f("ix_about_page_pkid"), table_name="about_page")
    op.drop_index(op.f("ix_about_page_date_updated"), table_name="about_page")
    op.drop_index(op.f("ix_about_page_date_created"), table_name="about_page")
    op.drop_table("about_page")
    # ### end Alembic commands ###
