# -*- coding: utf-8 -*-
import os

from dsg_lib.async_database_functions import database_operations
from fastapi.templating import Jinja2Templates
from loguru import logger
from sqlalchemy import Select, text
from sqlalchemy.exc import IntegrityError, OperationalError

from src.settings import settings

from .db_init import async_db
from .functions.db_guards import is_db_error

templates = Jinja2Templates(directory="templates")
templates.env.globals["plausible_domain"] = settings.plausible_domain
templates.env.globals["plausible_script_src"] = settings.plausible_script_src
# Surfaced as a persistent banner in base_app.html - if the dev fake-login
# bypass is reachable at all, that should never be silently invisible while
# poking around the app.
templates.env.globals["dev_fake_login_allowed"] = settings.dev_fake_login_allowed
# Gates dev-only UI (e.g. the raw-metrics "Data" card on the notes
# dashboard) - true for any non-production release_env, no separate opt-in
# flag needed since there's nothing to bypass, just extra debug output.
templates.env.globals["is_dev_environment"] = settings.is_dev_environment


def static_version(path: str) -> int:
    """
    Returns the mtime of a file under static/, for use as a cache-busting
    query string on its URL (?v=...). Without this, browsers can keep
    serving a stale cached copy of e.g. static/js/webauthn.js after it's
    edited, silently running old logic against a server that's since
    changed - a source of confusing, hard-to-reproduce bugs.
    """
    try:
        return int(os.path.getmtime(os.path.join("static", path)))
    except OSError:
        return 0


templates.env.globals["static_version"] = static_version

# mrie owns its own private database (Notes/Links tables included) - it's
# no longer sharing dsg's schema. Schema is managed by Alembic (see
# alembic/) for every real database; see startup_event()'s create_tables()
# call below for the one exception (the in-memory test driver).
db_ops = database_operations.DatabaseOperations(async_db)


async def startup_event():
    logger.info("starting up")

    # Alembic (see alembic/) is the schema manager for Postgres (dev + prod)
    # - applied out-of-band (devcontainer postCreateCommand, CI,
    # `make alembic-migrate`, or a deploy step), never on app boot. SQLite
    # (both the in-memory driver tests/conftest.py hard-codes, and the real
    # file-based driver `make run-dev-workers` uses) stays on create_tables()
    # instead: dsg_lib's schema_base picks a dialect-specific server_default
    # expression for date_created/date_updated (see db_tables.py's
    # SchemaBaseSQLite/SchemaBasePostgres split), and a frozen autogenerated
    # Alembic migration can't adapt to that the way create_all() does -
    # baking in Postgres's `CURRENT_TIMESTAMP AT TIME ZONE 'UTC'` breaks on
    # SQLite with a syntax error. Since SQLite's schema is always created
    # fresh (in-memory) or from an explicitly-reset file
    # (`make reset-dev-workers-db`), it never needs a real migration path.
    #
    # Under multiple uvicorn workers against the same DB (e.g.
    # `run-dev-workers`'s file-based driver), every worker process runs this
    # independently and they race here: create_tables() checks "does this
    # table exist yet?" then issues CREATE TABLE as two separate steps, not
    # atomically, so two workers can both see "not yet" and both try to
    # create it - the loser gets `OperationalError: table X already exists`.
    # Left unhandled, that crashes the worker, and uvicorn stops the
    # *entire* server when any worker fails to boot. Since the other
    # worker's table is exactly the schema this one would have created,
    # losing this race is harmless - log it and move on rather than taking
    # the whole app down over it.
    if not settings.is_postgres:
        try:
            await async_db.create_tables()
        except OperationalError as ex:
            if "already exists" not in str(ex):
                raise
            logger.debug(f"create_tables() lost a startup race to another worker: {ex}")

    if settings.is_postgres:
        # Alembic never runs as part of app boot (see above), so if the
        # out-of-band `alembic upgrade head` step was skipped, failed, or
        # only stamped the wrong revision (see PROJECT_STATUS.md's
        # Database section), the schema this app expects simply doesn't
        # exist. Left unchecked, the app boots cleanly and only fails
        # later, per-request - either as a confusing OperationalError, or
        # worse, silently as zeroed-out data, since several call sites
        # swallow a `DatabaseErrorResult` into an empty/default value (see
        # db_guards.py). Fail loudly here instead, the same "raise a clear
        # error" convention the optional-dependency pattern uses.
        migration_check = await db_ops.execute_one(
            text("SELECT 1 FROM alembic_version LIMIT 1")
        )
        if is_db_error(migration_check):
            raise RuntimeError(
                "Postgres schema has not been migrated - the "
                "'alembic_version' table is missing or unreadable. Run "
                "`alembic upgrade head` (see PROJECT_STATUS.md's Database "
                "section) before starting the app against this database."
            )

    # Dummy demo data is only ever seeded into a private local/in-memory dev
    # DB, never into a real Postgres deployment holding real imported notes.
    if not settings.is_postgres:
        from .db_tables import Users

        existing_users = await db_ops.read_query(Select(Users))
        if isinstance(existing_users, list) and len(existing_users) == 0:
            from .functions.demo_data import seed_demo_data

            # Same multi-worker race as create_tables() above: more than one
            # worker can see "users table is empty" before any of them has
            # finished inserting the demo admin user. The actual handling for
            # this lives inside seed_demo_data() itself (via safe_record() on
            # the create_one() result) - devsetgo-lib's create_one() catches
            # the UNIQUE-constraint violation internally and returns a
            # DatabaseErrorResult rather than raising, so it never reaches an
            # except clause here at all. This except is a defensive fallback
            # only, in case that ever changes back to raising.
            try:
                await seed_demo_data()
            except IntegrityError as ex:
                logger.debug(
                    f"seed_demo_data() lost a startup race to another worker: {ex}"
                )

    return None


async def shutdown_event():
    logger.info("shutting down")
    await async_db.disconnect()
    return None
